"""Merge per-paper .bib sidecars into one papers-bibliography.bib.

Design: see /Users/lucaarnaboldi/.claude/plans/we-now-need-to-misty-cloud.md

Run:
    uv run scripts/merge_bibs.py             # interactive (default; canonical run)
    uv run scripts/merge_bibs.py --dry-run   # parse + report, write nothing
    uv run scripts/merge_bibs.py --no-stop   # batch; auto-resolve duplicates

Outputs:
    papers-bibliography.bib                          (gitignored; regenerable)
    arxiv-papers/arXiv-YYMM-citation-map.json (one per sidecar; tracked in git)
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
import unicodedata
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

import bibtexparser
from bibtexparser.bparser import BibTexParser
from pylatexenc.latex2text import LatexNodes2Text

# bibtexparser logs an INFO line every time an @string is overwritten; sidecars
# with shared @string headers (e.g. arXiv-2506.bib) generate dozens of those.
logging.getLogger("bibtexparser.bibdatabase").setLevel(logging.WARNING)


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SIDECARS_DIR = REPO_ROOT / "arxiv-papers"
DEFAULT_OUTPUT = REPO_ROOT / "papers-bibliography.bib"

LATEX_DECODER = LatexNodes2Text(math_mode="text", keep_comments=False)

TITLE_STOPWORDS = {
    "a", "an", "the", "of", "for", "on", "in", "with", "and", "to", "from",
    "by", "via", "using", "towards", "toward",
}

JACCARD_THRESHOLD = 0.85

NOISE_FIELDS = {"abstract", "keywords", "note", "url", "annote", "file", "copyright"}

FIELD_ORDER = [
    "author", "editor", "title", "year", "month",
    "journal", "booktitle", "series",
    "volume", "number", "issue", "pages", "numpages",
    "publisher", "address", "organization", "school", "institution",
    "doi", "eprint", "archiveprefix", "primaryclass",
    "url", "isbn", "issn",
    "edition", "chapter", "type",
    "note",
]

HEADER = (
    "% Generated by scripts/merge_bibs.py - do not hand-edit.\n"
    "% Source: per-paper sidecars in arxiv-papers/arXiv-*.bib.\n"
    "% Editorial decisions (winners, tag renames) live in the tracked\n"
    "% arxiv-papers/arXiv-*-citation-map.json files.\n"
    "\n"
)


# ============================================================================
# Normalisation
# ============================================================================

def _decode_latex(s: str) -> str:
    try:
        return LATEX_DECODER.latex_to_text(s)
    except Exception:
        return s


def latex_clean_title(raw: str) -> str:
    """Strip LaTeX noise from a title — for matching/tag use ONLY, never for output."""
    text = re.sub(r"%.*", "", raw)
    text = re.sub(r"\$[^$]*\$", " MATH ", text)
    text = re.sub(r"\\\([^)]*\\\)", " MATH ", text)
    text = _decode_latex(text)
    text = text.replace("{", " ").replace("}", " ")
    text = text.replace("--", " ").replace("–", " ").replace("—", " ")
    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def title_tokens(raw: str) -> list[str]:
    return [t for t in latex_clean_title(raw).split() if t not in TITLE_STOPWORDS]


def normalize_doi(raw: str) -> str | None:
    if not raw:
        return None
    s = raw.strip().strip("{}").lower()
    s = re.sub(r"^(https?://)?(dx\.)?doi\.org/", "", s)
    s = re.sub(r"^doi:\s*", "", s)
    return s.strip().rstrip("/") or None


def normalize_eprint(raw: str) -> str | None:
    if not raw:
        return None
    s = raw.strip().strip("{}").lower()
    s = re.sub(r"^arxiv:\s*", "", s)
    s = re.sub(r"v\d+$", "", s)
    return s or None


def normalize_isbn(raw: str) -> str | None:
    if not raw:
        return None
    s = re.sub(r"[^0-9xX]", "", raw).lower()
    return s or None


def extract_identifiers(fields: dict[str, str]) -> set[str]:
    ids: set[str] = set()
    doi = normalize_doi(fields.get("doi", ""))
    if doi:
        ids.add(f"doi:{doi}")
        # arXiv-DOI bridge: 10.48550/arXiv.X is the same paper as eprint X
        m = re.match(r"^10\.48550/arxiv\.(.+)$", doi)
        if m:
            ids.add(f"eprint:{re.sub(r'v\d+$', '', m.group(1))}")
    eprint = normalize_eprint(fields.get("eprint", ""))
    if eprint:
        ids.add(f"eprint:{eprint}")
    isbn = normalize_isbn(fields.get("isbn", ""))
    if isbn:
        ids.add(f"isbn:{isbn}")
    return ids


# ============================================================================
# Author / lastname / year
# ============================================================================

def split_authors(author_str: str) -> list[str]:
    return [p.strip() for p in re.split(r"\s+and\s+", author_str, flags=re.IGNORECASE) if p.strip()]


def first_author_lastname(author_str: str) -> str:
    if not author_str:
        return "anon"
    authors = split_authors(author_str)
    if not authors:
        return "anon"
    first = authors[0]
    if "," in first:
        surname = first.split(",", 1)[0]
    else:
        tokens = first.split()
        surname = tokens[-1] if tokens else first
    surname = surname.replace("{", "").replace("}", "").strip()
    surname = _decode_latex(surname)
    surname = unicodedata.normalize("NFKD", surname)
    surname = "".join(c for c in surname if not unicodedata.combining(c))
    surname = surname.encode("ascii", "ignore").decode("ascii")
    surname = re.sub(r"[^a-z0-9]", "", surname.lower())
    return surname or "anon"


def extract_year(fields: dict[str, str]) -> str:
    raw = fields.get("year", "").strip().strip("{}")
    m = re.search(r"(\d{4})", raw)
    return m.group(1) if m else "nd"


# ============================================================================
# Dataclasses
# ============================================================================

@dataclass(eq=False)
class Entry:
    sidecar: str
    local_tag: str  # synthetic: equals base_local_tag for occurrence 1, else base#N
    base_local_tag: str  # the original key as it appears in the sidecar
    entry_type: str
    fields: dict[str, str]

    @property
    def title(self) -> str:
        return self.fields.get("title", "")

    @property
    def identifiers(self) -> set[str]:
        if not hasattr(self, "_ids"):
            self._ids = extract_identifiers(self.fields)
        return self._ids

    @property
    def title_bow_set(self) -> set[str]:
        if not hasattr(self, "_bow"):
            self._bow = set(title_tokens(self.title))
        return self._bow

    @property
    def title_words(self) -> list[str]:
        if not hasattr(self, "_tw"):
            self._tw = title_tokens(self.title)
        return self._tw

    @property
    def lastname(self) -> str:
        if not hasattr(self, "_ln"):
            self._ln = first_author_lastname(self.fields.get("author", ""))
        return self._ln

    @property
    def year(self) -> str:
        if not hasattr(self, "_yr"):
            self._yr = extract_year(self.fields)
        return self._yr

    @property
    def ref(self) -> str:
        return f"{self.sidecar}:{self.local_tag}"


@dataclass(eq=False)
class Group:
    canonical: Entry
    merged: list[Entry] = field(default_factory=list)
    global_tag: str | None = None
    # Tags this group's assignment collided with (forced our extension past
    # the baseline <lastname><year><titleword1>). Populated by assign_one_tag.
    collided_tags: list[str] = field(default_factory=list)

    def all_entries(self):
        yield self.canonical
        yield from self.merged

    def add(self, entry: Entry) -> None:
        self.merged.append(entry)

    def make_canonical(self, entry: Entry) -> None:
        if entry is self.canonical:
            return
        if not any(e is entry for e in self.merged):
            raise ValueError("entry is not in this group")
        self.merged = [e for e in self.merged if e is not entry]
        old = self.canonical
        self.canonical = entry
        self.merged.append(old)


# ============================================================================
# Matching
# ============================================================================

@dataclass
class MatchResult:
    kind: str  # "definitive" | "canonical_equal" | "candidate" | "none"
    group: "Group | None" = None
    jaccard: float = 0.0


def jaccard(a: set[str], b: set[str]) -> float:
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def canonicalise_for_equality(fields: dict[str, str]) -> dict[str, str]:
    out = {}
    for k, v in fields.items():
        kl = k.lower()
        if kl in NOISE_FIELDS:
            continue
        out[kl] = re.sub(r"\s+", " ", v.strip())
    return out


def canonical_equal(a: Entry, b: Entry) -> bool:
    return canonicalise_for_equality(a.fields) == canonicalise_for_equality(b.fields)


def find_match(entry: Entry, groups: list[Group]) -> MatchResult:
    best = MatchResult(kind="none")
    for g in groups:
        other = g.canonical
        if entry.identifiers and other.identifiers:
            if entry.identifiers & other.identifiers:
                return MatchResult(kind="definitive", group=g)
            continue  # definitively different — skip even title comparison
        if canonical_equal(entry, other):
            return MatchResult(kind="canonical_equal", group=g)
        if entry.title_bow_set and other.title_bow_set:
            j = jaccard(entry.title_bow_set, other.title_bow_set)
            if j >= JACCARD_THRESHOLD and j > best.jaccard:
                best = MatchResult(kind="candidate", group=g, jaccard=j)
    return best


# ============================================================================
# Resolution
# ============================================================================

def auto_pick_canonical(entries: list[Entry]) -> Entry:
    """Tiebreaker chain for --no-stop and as the heuristic shown in the prompt."""
    def score(e: Entry):
        has_doi = bool(normalize_doi(e.fields.get("doi", "")))
        has_eprint = bool(normalize_eprint(e.fields.get("eprint", "")))
        published = bool(e.fields.get("pages") and e.fields.get("volume"))
        length = sum(
            len(v) for k, v in e.fields.items()
            if k.lower() not in {"abstract", "keywords"}
        )
        return (has_doi, has_eprint, published, length)
    return max(entries, key=score)


def _render_entry(entry: Entry, label: str) -> str:
    lines = [f"[{label}] {entry.ref}  (@{entry.entry_type})"]
    shown_keys = set()
    for fname in ("title", "author", "year", "journal", "booktitle",
                  "publisher", "doi", "eprint", "pages", "volume", "number"):
        for k, v in entry.fields.items():
            if k.lower() == fname and k not in shown_keys:
                shown_keys.add(k)
                lines.append(f"  {fname:10s}: {v}")
                break
    return "\n".join(lines)


def prompt_user(
    new_entry: Entry,
    group: Group,
    jaccard_score: float,
    *,
    force_merge: bool = False,
    progress_label: str | None = None,
) -> str:
    auto = auto_pick_canonical([group.canonical, new_entry])
    auto_label = "NEW" if auto is new_entry else "CURRENT"
    bar = "=" * 72
    print(f"\n{bar}", flush=True)
    if progress_label:
        print(f"[{progress_label}]", flush=True)
    if force_merge:
        print(
            f"In-sidecar duplicate local tag '{new_entry.base_local_tag}' "
            f"in {new_entry.sidecar} -- must pick one entry "
            "(the .tex source can't disambiguate)",
            flush=True,
        )
    else:
        print(f"Potential duplicate  (BoW Jaccard {jaccard_score:.2f})", flush=True)
    print(bar, flush=True)
    print(_render_entry(group.canonical, "CURRENT"), flush=True)
    print(flush=True)
    print(_render_entry(new_entry, "NEW"), flush=True)
    print(flush=True)
    print(f"Auto-heuristic would pick: {auto_label}", flush=True)
    print(flush=True)
    print("Choose:", flush=True)
    print("  [y] yes, merge - keep CURRENT as canonical", flush=True)
    print("  [r] yes, merge - replace canonical with NEW", flush=True)
    if not force_merge:
        print("  [n] no, these are distinct papers", flush=True)
    print(f"  [enter] accept auto-heuristic pick ({auto_label})", flush=True)
    print("  [q] quit (progress already saved; re-run to resume)", flush=True)
    valid = "y/r/q" if force_merge else "y/r/n/q"
    while True:
        try:
            ans = input("> ").strip().lower()
        except EOFError:
            return "quit"
        if ans == "":
            return "merge_replace" if auto is new_entry else "merge_keep_current"
        if ans in ("y", "yes"):
            return "merge_keep_current"
        if ans in ("r", "replace"):
            return "merge_replace"
        if ans in ("n", "no") and not force_merge:
            return "distinct"
        if ans in ("q", "quit"):
            return "quit"
        print(f"(answer {valid} or enter for auto)", flush=True)


def resolve_candidate(
    new_entry: Entry,
    group: Group,
    jaccard_score: float,
    no_stop: bool,
    *,
    force_merge: bool = False,
    progress_label: str | None = None,
) -> str:
    if no_stop:
        winner = auto_pick_canonical([group.canonical, new_entry])
        tag = "[auto:force]" if force_merge else "[auto]"
        if winner is new_entry:
            sys.stderr.write(
                f"{tag} {new_entry.ref} replaces canonical {group.canonical.ref}\n"
            )
            return "merge_replace"
        sys.stderr.write(
            f"{tag} {new_entry.ref} merged into {group.canonical.ref}\n"
        )
        return "merge_keep_current"
    return prompt_user(
        new_entry, group, jaccard_score,
        force_merge=force_merge, progress_label=progress_label,
    )


# ============================================================================
# Tag generation
# ============================================================================

def build_tag(g: Group, word_count: int) -> str:
    e = g.canonical
    words = e.title_words[:word_count] if e.title_words else ["untitled"]
    return f"{e.lastname}{e.year}{''.join(words)}"


def assign_one_tag(group: Group, claimed: set[str]) -> None:
    """Pick a global tag for `group`, avoiding any tag already in `claimed`.

    Baseline: <lastname><year><titleword1>. On collision, extend by adding
    the next cleaned title word; if title words run out, append a/b/c.
    Records every claimed tag we bumped into in `group.collided_tags`
    (forensic info written to the citation map). Mutates `group.global_tag`.
    (Incremental, called once per new group — so collisions among groups
    created in the same run are resolved asymmetrically, with whoever was
    created first keeping the shorter tag.)
    """
    max_words = max(len(group.canonical.title_words), 1)
    wc = 1
    collisions: list[str] = []
    while True:
        tag = build_tag(group, wc)
        if tag not in claimed:
            group.global_tag = tag
            group.collided_tags = collisions
            return
        collisions.append(tag)
        if wc < max_words:
            wc += 1
            continue
        # Title exhausted — append a/b/c suffix to the longest form.
        idx = 0
        while True:
            cand = tag + chr(ord("a") + idx)
            if cand not in claimed:
                group.global_tag = cand
                group.collided_tags = collisions
                return
            collisions.append(cand)
            idx += 1


# ============================================================================
# Parsing / output
# ============================================================================

def parse_sidecar(path: Path) -> list[Entry]:
    parser = BibTexParser(common_strings=True)
    parser.ignore_nonstandard_types = False
    parser.homogenize_fields = False
    parser.interpolate_strings = True
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        db = bibtexparser.load(f, parser=parser)
    entries: list[Entry] = []
    occurrence_count: dict[str, int] = {}
    for raw in db.entries:
        base_tag = raw["ID"]
        occurrence_count[base_tag] = occurrence_count.get(base_tag, 0) + 1
        occ = occurrence_count[base_tag]
        # Synthetic local_tag for occurrences past the first, so refs stay
        # unique downstream. The base_tag is what the user's .tex source cites
        # and what the cite-rewriter will look up in the citation map.
        local_tag = base_tag if occ == 1 else f"{base_tag}#{occ}"
        if occ > 1:
            sys.stderr.write(
                f"[dup-local-tag] {path.name}:{base_tag} occurrence #{occ}; "
                "will be force-merged with the first occurrence's group "
                "(same base tag => only one entry can win)\n"
            )
        entry_type = raw["ENTRYTYPE"]
        fields = {
            k.lower(): v for k, v in raw.items() if k not in ("ID", "ENTRYTYPE")
        }
        entries.append(Entry(
            sidecar=path.name,
            local_tag=local_tag,
            base_local_tag=base_tag,
            entry_type=entry_type,
            fields=fields,
        ))
    return entries


def format_entry(g: Group) -> str:
    e = g.canonical
    lines = [f"@{e.entry_type.lower()}{{{g.global_tag},"]
    written = set()
    for fname in FIELD_ORDER:
        for k, v in e.fields.items():
            if k.lower() == fname and k not in written:
                lines.append(f"  {fname} = {{{v}}},")
                written.add(k)
                break
    for k in sorted(e.fields.keys()):
        if k in written:
            continue
        lines.append(f"  {k.lower()} = {{{e.fields[k]}}},")
    lines.append("}")
    return "\n".join(lines)


def write_bib(path: Path, groups: list[Group]) -> None:
    sorted_groups = sorted(groups, key=lambda g: g.global_tag or "")
    body = "\n\n".join(format_entry(g) for g in sorted_groups)
    path.write_text(HEADER + body + "\n", encoding="utf-8")


def save_progress(
    sidecars_dir: Path, sidecars: list[Path], groups: list[Group]
) -> None:
    """Persist the citation maps so an interrupted interactive run can resume.

    Only writes the maps (not the merged bib). On the next invocation, the
    existing-maps idempotency path picks up already-decided entries and skips
    re-prompting them.
    """
    write_maps(sidecars_dir, sidecars, groups)


def write_maps(sidecars_dir: Path, sidecars: list[Path], groups: list[Group]) -> None:
    by_sidecar: dict[str, dict[str, dict]] = {s.name: {} for s in sidecars}
    for g in groups:
        canonical_ref = g.canonical.ref
        merged_from = [e.ref for e in g.merged]
        for e in g.all_entries():
            if e.sidecar not in by_sidecar:
                continue
            if e is g.canonical:
                rec: dict = {
                    "global_tag": g.global_tag,
                    "reason": "assigned",
                }
                # Tag-disambiguation forensics: only present when the assigned
                # global_tag was extended past the baseline because some other
                # group already claimed that baseline.
                baseline = build_tag(g, 1) if g.global_tag else None
                if baseline and g.global_tag != baseline:
                    rec["tag_baseline"] = baseline
                if g.collided_tags:
                    rec["collided_with"] = list(g.collided_tags)
                # Cross-sidecar-duplicate forensics: which loser entries
                # merged into this canonical (the inverse of merged_into on
                # the losers' records).
                if merged_from:
                    rec["merged_from"] = list(merged_from)
                by_sidecar[e.sidecar][e.local_tag] = rec
            else:
                by_sidecar[e.sidecar][e.local_tag] = {
                    "global_tag": g.global_tag,
                    "reason": "merged-away",
                    "merged_into": canonical_ref,
                }
    for s in sidecars:
        map_path = sidecars_dir / f"{s.stem}-citation-map.json"
        data = {
            "sidecar": s.name,
            "mappings": dict(sorted(by_sidecar[s.name].items())),
        }
        map_path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )


# ============================================================================
# Main
# ============================================================================

def precount_prompts(
    sidecars: list[Path],
    entries_by_sidecar: dict[str, list[Entry]],
    existing_maps: dict[str, dict[str, dict]],
) -> tuple[int, dict[str, int]]:
    """Estimate prompts that will fire in interactive mode.

    Returns ``(cross_sidecar_total, per_sidecar_in_file_total)``. Simulates
    the main pipeline assuming the user picks 'merge_keep_current' for each
    candidate (the most common choice); if you instead pick 'distinct' early
    on, later counts can drift slightly. Good enough for a progress display.
    """
    cross_total = 0
    in_file_total: dict[str, int] = {s.name: 0 for s in sidecars}

    groups: list[Group] = []
    group_by_tag: dict[str, Group] = {}
    same_sidecar: dict[tuple[str, str], Group] = {}
    placed: set[str] = set()

    for s in sidecars:
        for e in entries_by_sidecar[s.name]:
            rec = existing_maps[s.name].get(e.local_tag)
            if rec is None or rec.get("reason") != "assigned":
                continue
            gt = rec["global_tag"]
            if gt in group_by_tag:
                continue
            g = Group(canonical=e, global_tag=gt)
            groups.append(g)
            group_by_tag[gt] = g
            same_sidecar.setdefault((e.sidecar, e.base_local_tag), g)
            placed.add(e.ref)

    for s in sidecars:
        for e in entries_by_sidecar[s.name]:
            rec = existing_maps[s.name].get(e.local_tag)
            if rec is None or rec.get("reason") != "merged-away":
                continue
            gt = rec["global_tag"]
            g = group_by_tag.get(gt)
            if g is None:
                continue
            g.add(e)
            same_sidecar.setdefault((e.sidecar, e.base_local_tag), g)
            placed.add(e.ref)

    for s in sidecars:
        for entry in entries_by_sidecar[s.name]:
            if entry.ref in placed:
                continue
            forced = same_sidecar.get((entry.sidecar, entry.base_local_tag))
            if forced is not None:
                if not canonical_equal(entry, forced.canonical):
                    in_file_total[entry.sidecar] += 1
                forced.add(entry)
                placed.add(entry.ref)
                continue
            match = find_match(entry, groups)
            if match.kind in ("definitive", "canonical_equal"):
                match.group.add(entry)
                same_sidecar.setdefault((entry.sidecar, entry.base_local_tag), match.group)
            elif match.kind == "candidate":
                cross_total += 1
                # Pretend the user picks merge_keep_current (don't spawn a new group).
                match.group.add(entry)
                same_sidecar.setdefault((entry.sidecar, entry.base_local_tag), match.group)
            else:
                g = Group(canonical=entry)
                groups.append(g)
                same_sidecar.setdefault((entry.sidecar, entry.base_local_tag), g)
            placed.add(entry.ref)

    return cross_total, in_file_total


def load_existing_maps(
    sidecars_dir: Path, sidecars: list[Path]
) -> dict[str, dict[str, dict]]:
    out: dict[str, dict[str, dict]] = {}
    for s in sidecars:
        map_path = sidecars_dir / f"{s.stem}-citation-map.json"
        if map_path.exists():
            data = json.loads(map_path.read_text(encoding="utf-8"))
            out[s.name] = data.get("mappings", {})
        else:
            out[s.name] = {}
    return out


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--no-stop", action="store_true",
                   help="Auto-resolve duplicates (DOI/eprint/published/longest).")
    p.add_argument("--dry-run", action="store_true",
                   help="Parse and report; write nothing.")
    p.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    p.add_argument("--sidecars-dir", type=Path, default=DEFAULT_SIDECARS_DIR)
    return p.parse_args()


def main() -> int:
    args = parse_args()

    sidecars = sorted(args.sidecars_dir.glob("arXiv-*.bib"))
    if not sidecars:
        print(
            f"No sidecars matching arXiv-*.bib in {args.sidecars_dir}",
            file=sys.stderr,
        )
        return 2

    print(
        f"Found {len(sidecars)} sidecar(s): "
        + ", ".join(s.name for s in sidecars),
        file=sys.stderr,
    )

    existing_maps = load_existing_maps(args.sidecars_dir, sidecars)

    # Cross-check existing bib if present (warn-only)
    if args.output.exists():
        with open(args.output, "r", encoding="utf-8") as f:
            existing_db = bibtexparser.load(f, parser=BibTexParser(common_strings=True))
        bib_keys = {e["ID"] for e in existing_db.entries}
        assigned_tags = {
            rec["global_tag"]
            for sidecar_map in existing_maps.values()
            for rec in sidecar_map.values()
            if rec.get("reason") == "assigned"
        }
        missing = assigned_tags - bib_keys
        if missing:
            preview = ", ".join(sorted(missing)[:5])
            print(
                f"[stale-bib] {len(missing)} mapped global tag(s) missing from "
                f"{args.output.name} (will regenerate): {preview}...",
                file=sys.stderr,
            )

    entries_by_sidecar: dict[str, list[Entry]] = {
        s.name: parse_sidecar(s) for s in sidecars
    }
    total_in = sum(len(es) for es in entries_by_sidecar.values())
    print(
        f"Parsed {total_in} entries across {len(sidecars)} sidecars.",
        file=sys.stderr,
    )

    # Reconstruct groups from existing maps (idempotency).
    # Tracks the group that the FIRST occurrence of each (sidecar, base_tag)
    # landed in, so subsequent occurrences (in-sidecar duplicates) get
    # force-merged into the same group rather than spawning a new one.
    groups: list[Group] = []
    group_by_global_tag: dict[str, Group] = {}
    same_sidecar_canonicals: dict[tuple[str, str], Group] = {}
    placed: set[str] = set()

    for s in sidecars:
        for entry in entries_by_sidecar[s.name]:
            rec = existing_maps[s.name].get(entry.local_tag)
            if rec is None or rec.get("reason") != "assigned":
                continue
            gt = rec["global_tag"]
            if gt in group_by_global_tag:
                print(
                    f"[stale-map] duplicate canonical for '{gt}': "
                    f"{group_by_global_tag[gt].canonical.ref} and {entry.ref}; "
                    "keeping first, re-processing second",
                    file=sys.stderr,
                )
                continue
            g = Group(canonical=entry, global_tag=gt)
            g.collided_tags = list(rec.get("collided_with", []))
            groups.append(g)
            group_by_global_tag[gt] = g
            same_sidecar_canonicals.setdefault((entry.sidecar, entry.base_local_tag), g)
            placed.add(entry.ref)

    for s in sidecars:
        for entry in entries_by_sidecar[s.name]:
            rec = existing_maps[s.name].get(entry.local_tag)
            if rec is None or rec.get("reason") != "merged-away":
                continue
            gt = rec["global_tag"]
            g = group_by_global_tag.get(gt)
            if g is None:
                print(
                    f"[stale-map] merged-away entry {entry.ref} -> '{gt}' has "
                    "no canonical; will re-process",
                    file=sys.stderr,
                )
                continue
            g.add(entry)
            same_sidecar_canonicals.setdefault((entry.sidecar, entry.base_local_tag), g)
            placed.add(entry.ref)

    # Process new entries. Tags are assigned incrementally so we can write
    # maps (with valid global_tags) after every interactive decision.
    claimed: set[str] = {g.global_tag for g in groups if g.global_tag}
    stats: dict[str, int] = defaultdict(int)
    interactive = not (args.no_stop or args.dry_run)

    cross_total = 0
    in_file_total: dict[str, int] = {s.name: 0 for s in sidecars}
    cross_done = 0
    in_file_done: dict[str, int] = {s.name: 0 for s in sidecars}
    if interactive:
        cross_total, in_file_total = precount_prompts(
            sidecars, entries_by_sidecar, existing_maps
        )
        per_sidecar_lines = [
            f"    {name}: {n} in-file" for name, n in in_file_total.items() if n
        ]
        print(
            f"\nInteractive prompts pending (estimate): "
            f"{cross_total} cross-sidecar + {sum(in_file_total.values())} in-file",
            file=sys.stderr,
        )
        if per_sidecar_lines:
            print("\n".join(per_sidecar_lines), file=sys.stderr)
        print("", file=sys.stderr)

    def _record_first_occurrence(entry: Entry, group: Group) -> None:
        same_sidecar_canonicals.setdefault(
            (entry.sidecar, entry.base_local_tag), group
        )

    def _new_group(entry: Entry) -> Group:
        g = Group(canonical=entry)
        groups.append(g)
        assign_one_tag(g, claimed)
        claimed.add(g.global_tag)
        _record_first_occurrence(entry, g)
        return g

    for s in sidecars:
        for entry in entries_by_sidecar[s.name]:
            if entry.ref in placed:
                continue

            forced = same_sidecar_canonicals.get(
                (entry.sidecar, entry.base_local_tag)
            )

            if forced is not None:
                # Same base local_tag already seen in this sidecar.
                # Force-merge: the .tex source cites \cite{base_tag} and the
                # rewriter can only point it at one entry, so "distinct" isn't
                # an option here.
                if canonical_equal(entry, forced.canonical):
                    stats["auto_merge_in_sidecar_canonical"] += 1
                    forced.add(entry)
                    sys.stderr.write(
                        f"[auto:in-sidecar-canon] {entry.ref} -> {forced.canonical.ref}\n"
                    )
                elif args.dry_run:
                    stats["in_sidecar_would_prompt"] += 1
                    forced.add(entry)
                else:
                    if interactive:
                        save_progress(args.sidecars_dir, sidecars, groups)
                    progress_label = None
                    if interactive:
                        in_file_done[entry.sidecar] += 1
                        progress_label = (
                            f"{entry.sidecar} in-file disambiguation "
                            f"{in_file_done[entry.sidecar]} of "
                            f"{in_file_total[entry.sidecar]}"
                        )
                    decision = resolve_candidate(
                        entry, forced, 1.0, args.no_stop,
                        force_merge=True, progress_label=progress_label,
                    )
                    if decision == "merge_keep_current":
                        stats["in_sidecar_kept_current"] += 1
                        forced.add(entry)
                    elif decision == "merge_replace":
                        stats["in_sidecar_replaced"] += 1
                        forced.add(entry)
                        forced.make_canonical(entry)
                    elif decision == "quit":
                        save_progress(args.sidecars_dir, sidecars, groups)
                        print(
                            "Aborted by user. Progress saved -- re-run to resume.",
                            file=sys.stderr,
                        )
                        return 3
                placed.add(entry.ref)
                if interactive:
                    save_progress(args.sidecars_dir, sidecars, groups)
                continue

            # First occurrence in this sidecar -- normal cross-sidecar match.
            match = find_match(entry, groups)

            if match.kind == "definitive":
                stats["auto_merge_identifier"] += 1
                match.group.add(entry)
                _record_first_occurrence(entry, match.group)
                sys.stderr.write(
                    f"[auto:id] {entry.ref} -> {match.group.canonical.ref}\n"
                )
            elif match.kind == "canonical_equal":
                stats["auto_merge_canonical"] += 1
                match.group.add(entry)
                _record_first_occurrence(entry, match.group)
                sys.stderr.write(
                    f"[auto:canon] {entry.ref} -> {match.group.canonical.ref}\n"
                )
            elif match.kind == "candidate":
                if args.dry_run:
                    stats["would_prompt"] += 1
                    _new_group(entry)
                else:
                    if interactive:
                        save_progress(args.sidecars_dir, sidecars, groups)
                    progress_label = None
                    if interactive:
                        cross_done += 1
                        progress_label = (
                            f"global cross-sidecar disambiguation "
                            f"{cross_done} of {cross_total}"
                        )
                    decision = resolve_candidate(
                        entry, match.group, match.jaccard, args.no_stop,
                        progress_label=progress_label,
                    )
                    if decision == "merge_keep_current":
                        stats["merged_kept_current"] += 1
                        match.group.add(entry)
                        _record_first_occurrence(entry, match.group)
                    elif decision == "merge_replace":
                        stats["merged_replaced"] += 1
                        match.group.add(entry)
                        match.group.make_canonical(entry)
                        _record_first_occurrence(entry, match.group)
                    elif decision == "distinct":
                        stats["kept_distinct"] += 1
                        _new_group(entry)
                    elif decision == "quit":
                        save_progress(args.sidecars_dir, sidecars, groups)
                        print(
                            "Aborted by user. Progress saved -- re-run to resume.",
                            file=sys.stderr,
                        )
                        return 3
            else:
                stats["new"] += 1
                _new_group(entry)

            placed.add(entry.ref)
            if interactive:
                save_progress(args.sidecars_dir, sidecars, groups)

    stats["tag_collisions_extended"] = sum(
        1 for g in groups if g.global_tag and g.global_tag != build_tag(g, 1)
    )

    print(f"\nGroups: {len(groups)}  (entries in: {total_in})", file=sys.stderr)
    for k, v in sorted(stats.items()):
        print(f"  {k}: {v}", file=sys.stderr)

    if args.dry_run:
        print("\n(dry-run - no files written)", file=sys.stderr)
        return 0

    write_bib(args.output, groups)
    write_maps(args.sidecars_dir, sidecars, groups)

    def _display_path(p: Path) -> str:
        try:
            return str(p.relative_to(REPO_ROOT))
        except ValueError:
            return str(p)

    print(f"\nWrote {_display_path(args.output)}", file=sys.stderr)
    print(
        f"Wrote {len(sidecars)} citation map(s) under "
        f"{_display_path(args.sidecars_dir)}/",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
